// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	blob "github.com/kopia/kopia/repo/blob"

	mock "github.com/stretchr/testify/mock"
)

// kopiaStorageFlags is an autogenerated mock type for the kopiaStorageFlags type
type kopiaStorageFlags struct {
	mock.Mock
}

// Connect provides a mock function with given fields: ctx, isCreate, formatVersion
func (_m *kopiaStorageFlags) Connect(ctx context.Context, isCreate bool, formatVersion int) (blob.Storage, error) {
	ret := _m.Called(ctx, isCreate, formatVersion)

	var r0 blob.Storage
	if rf, ok := ret.Get(0).(func(context.Context, bool, int) blob.Storage); ok {
		r0 = rf(ctx, isCreate, formatVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blob.Storage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, bool, int) error); ok {
		r1 = rf(ctx, isCreate, formatVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Setup provides a mock function with given fields: flags
func (_m *kopiaStorageFlags) Setup(flags string) error {
	ret := _m.Called(flags)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
