// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	uploader "github.com/vmware-tanzu/velero/pkg/uploader"

	v1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
)

// BackupperFactory is an autogenerated mock type for the BackupperFactory type
type BackupperFactory struct {
	mock.Mock
}

// NewBackupper provides a mock function with given fields: _a0, _a1
func (_m *BackupperFactory) NewBackupper(_a0 context.Context, _a1 *v1.Backup) (uploader.Backupper, error) {
	ret := _m.Called(_a0, _a1)

	var r0 uploader.Backupper
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) uploader.Backupper); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uploader.Backupper)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
