// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"

	uploader "github.com/vmware-tanzu/velero/pkg/uploader"
)

// Restorer is an autogenerated mock type for the Restorer type
type Restorer struct {
	mock.Mock
}

// RestorePodVolumes provides a mock function with given fields: _a0, _a1
func (_m *Restorer) RestorePodVolumes(_a0 logrus.FieldLogger, _a1 uploader.RestoreData) []error {
	ret := _m.Called(_a0, _a1)

	var r0 []error
	if rf, ok := ret.Get(0).(func(logrus.FieldLogger, uploader.RestoreData) []error); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}
